// <auto-generated />
using System;
using ContentGapAnalyzer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContentGapAnalyzer.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617142320_InitialSchemaFix")]
    partial class InitialSchemaFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.AnalysisSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GapReportId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GapReportId");

                    b.ToTable("AnalysisSessions");
                });

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.AnalyticsSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgClickThroughRate")
                        .HasColumnType("float");

                    b.Property<double>("AvgEngagementRate")
                        .HasColumnType("float");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("NewSubscribers")
                        .HasColumnType("bigint");

                    b.Property<long>("NewViews")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubscriberCount")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalViews")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("WatchTimeMinutes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("AnalyticsSnapshots");
                });

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.CachedTrendResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HitCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CachedTrendResults");
                });

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("SubscriberCount")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("TotalViews")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("VideoCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("ChannelId")
                        .HasName("AK_Channels_ChannelId");

                    b.HasIndex("ChannelId")
                        .IsUnique()
                        .HasDatabaseName("IX_Channels_ChannelId");

                    b.ToTable("Channels", (string)null);
                });

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.GapReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudiencePainPointsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("audience_pain_points_json");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("channel_id");

                    b.Property<double>("CompetitionDifficulty")
                        .HasColumnType("float")
                        .HasColumnName("competition_score");

                    b.Property<string>("ContentGapsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_gaps_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CtrOptimizationSuggestionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ctr_optimization_suggestions_json");

                    b.Property<string>("HookImprovementsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hook_improvements_json");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MissedOpportunitiesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("missed_opportunities_json");

                    b.Property<double>("OpportunityScore")
                        .HasColumnType("float")
                        .HasColumnName("gap_score");

                    b.Property<string>("RawAiResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_ai_response");

                    b.Property<string>("RetentionImprovementsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("retention_improvements_json");

                    b.Property<string>("SeoRecommendationsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("seo_recommendations_json");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("StrengthsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("strengths_json");

                    b.Property<double>("TrendGrowth")
                        .HasColumnType("float")
                        .HasColumnName("trend_score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("video_id");

                    b.Property<string>("VideoTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("video_title");

                    b.Property<string>("ViralPotentialAnalysis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("viral_potential_analysis");

                    b.Property<string>("WeaknessesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("weaknesses_json");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("Content_Gap_Analyses", (string)null);
                });

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.HistoricalStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<double>("ClickThroughRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("EngagementRate")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("Subscribers")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.Property<long>("WatchTimeMinutes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("HistoricalStatistics");
                });

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.Opportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("AvgViews")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CompetitionScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DemandScore")
                        .HasColumnType("float");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<double>("GapScore")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpportunityTagsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SearchVolume")
                        .HasColumnType("bigint");

                    b.Property<double>("TrendScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Opportunities");
                });

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageViewDuration")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<double>("ClickThroughRate")
                        .HasColumnType("float");

                    b.Property<long>("CommentCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("LikeCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.Property<long>("WatchTimeMinutes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("IX_Videos_ChannelId");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("IX_Videos_VideoId");

                    b.ToTable("Videos", (string)null);
                });

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.VideoAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudiencePainPoints")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CompetitionDifficulty")
                        .HasColumnType("float");

                    b.Property<string>("ContentGaps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CtrOptimizationSuggestions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HookImprovements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissedOpportunities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OpportunityScore")
                        .HasColumnType("float");

                    b.Property<string>("RetentionImprovements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoRecommendations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TrendGrowth")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViralPotentialAnalysis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoAnalyses");
                });

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.AnalysisSession", b =>
                {
                    b.HasOne("ContentGapAnalyzer.Domain.Entities.GapReport", "GapReport")
                        .WithMany("AnalysisSessions")
                        .HasForeignKey("GapReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GapReport");
                });

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.AnalyticsSnapshot", b =>
                {
                    b.HasOne("ContentGapAnalyzer.Domain.Entities.Channel", "Channel")
                        .WithMany("AnalyticsSnapshots")
                        .HasForeignKey("ChannelId")
                        .HasPrincipalKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AnalyticsSnapshots_Channels_ChannelId");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.GapReport", b =>
                {
                    b.HasOne("ContentGapAnalyzer.Domain.Entities.Video", "Video")
                        .WithMany("GapReports")
                        .HasForeignKey("VideoId")
                        .HasPrincipalKey("VideoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_GapReports_Videos_VideoId");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.HistoricalStatistic", b =>
                {
                    b.HasOne("ContentGapAnalyzer.Domain.Entities.Channel", "Channel")
                        .WithMany("HistoricalStatistics")
                        .HasForeignKey("ChannelId")
                        .HasPrincipalKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HistoricalStatistics_Channels_ChannelId");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.Video", b =>
                {
                    b.HasOne("ContentGapAnalyzer.Domain.Entities.Channel", "Channel")
                        .WithMany("Videos")
                        .HasForeignKey("ChannelId")
                        .HasPrincipalKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Videos_Channels_ChannelId");

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.Channel", b =>
                {
                    b.Navigation("AnalyticsSnapshots");

                    b.Navigation("HistoricalStatistics");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.GapReport", b =>
                {
                    b.Navigation("AnalysisSessions");
                });

            modelBuilder.Entity("ContentGapAnalyzer.Domain.Entities.Video", b =>
                {
                    b.Navigation("GapReports");
                });
#pragma warning restore 612, 618
        }
    }
}
